/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kanbanboard;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Dashbord extends javax.swing.JFrame {
    
   public  int num4;
   

    /**
     * Creates new form Dashboard
     */
    public Dashbord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    /**
     ## CODE ATTRIBUTION 
#References generated from W3Schools httpswww.w3schools.comcscs_user_input.php

generated from WebGentle httpswww.youtube.comwatchv=vWN4Zmkd4hM

KevinTheTechLover httpswww.youtube.comwatchv=0n_-Jwb2Xkc

Gamaliel Menil httpswww.youtube.comwatchv=az8mHaJXpRE

generated from W3Schools httpswww.w3schools.comcscs_user_input.php

Arrays in java: Microsoft. (n.d.). Arrays in Jvaa. Retrieved April 28, 2023, from https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/

Console class in java: Microsoft. (n.d.). Console Class. Retrieved April 28, 2023, from https://docs.microsoft.com/en-us/dotnet/api/system.console?view=net-6.0

switch statement in java: Microsoft. (n.d.). switch statement (Java reference). Retrieved April 28, 2023, from https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/switch string class in java: Microsoft. (n.d.). String Class. Retrieved April 28, 2023, from https://docs.microsoft.com/en-us/dotnet/api/system.string?view=net-6.0 double data type in java: Microsoft. (n.d.). Floating-Point Numeric Types. Retrieved April 28, 2023, from https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types

Object-oriented programming (OOP) concepts: Wikipedia contributors. (2023, April 22). Object-oriented programming. In Wikipedia, The Free Encyclopedia. Retrieved April 28, 2023, from https://en.wikipedia.org/wiki/Object-oriented_programming

## How the programs works

This is a Java Swing class that represents the login screen of a Kanban board application. The user can enter their username and password and then click the "LOGIN" button to log in to the application. If the user doesn't have an account, they can click the "Don't Have an Account? Register here." button to be redirected to the registration screen.

The class contains several Swing components such as a JLabel, a JTextField, a JPasswordField, and two JButtons. The initComponents() method initializes these components and sets up their properties such as their text, font, and color.

The loginbtnMouseClicked() method is called when the user clicks on the "LOGIN" button. It reads the username and password entered by the user and then checks if they match the ones stored in a file. If the username and password are correct, it displays a message saying "Login Successful" and redirects the user to the Kanban board screen. If the username and password are incorrect, it displays an error message saying "Invalid Username or Password".

The registerbtnActionPerformed() method is called when the user clicks on the "Don't Have an Account? Register here." button. It redirects the user to the registration screen.
 
      
     
     **/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAddTasks = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        btnComingSoon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0,0, 0, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddTasks.setBackground(new java.awt.Color(0, 0, 204));
        btnAddTasks.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        btnAddTasks.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTasks.setText("Add Tasks");
        btnAddTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTasksActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddTasks, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 75, 110, 34));

        btnQuit.setBackground(new java.awt.Color(0, 0, 204));
        btnQuit.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(255, 255, 255));
        btnQuit.setText("QUIT");
        btnQuit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitMouseClicked(evt);
            }
        });
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 225, 110, 33));

        btnComingSoon.setBackground(new java.awt.Color(0, 0, 204));
        btnComingSoon.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        btnComingSoon.setForeground(new java.awt.Color(255, 255, 255));
        btnComingSoon.setText("Show Report");
        btnComingSoon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComingSoonMouseClicked(evt);
            }
        });
        btnComingSoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComingSoonActionPerformed(evt);
            }
        });
        jPanel1.add(btnComingSoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 150, 110, 32));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 80, 50));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("1)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 60, 40));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("2)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 60, 30));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("3)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 224, 60, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 300, 320));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dr. M.S Fanana\\Videos\\333.jpg")); // NOI18N
        jLabel2.setText(" ");
        jLabel2.setPreferredSize(new java.awt.Dimension(1070, 700));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-470, -40, 1310, 1070));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean login(String login){
     
        
       // int num = Integer.parseInt(JOptionPane.showInputDialog("Enter number of tasks"));
    
    
    return true;
    }
    
    private void btnAddTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTasksActionPerformed
        // TODO add your handling code here:
        
        Dashbord db = new Dashbord();
        String log = "true";
        
        int num = Integer.parseInt(JOptionPane.showInputDialog("Enter number of tasks?"));
       int num4= num;
      
        
        if(db.login(log)== true){
            
            
            
           TaskEx1 ts = new TaskEx1();
           ts.methods();
                    JOptionPane.showMessageDialog(null, ts.printTaskDetails(ts.name, ts.desc, ts.dev, ts.dur));

           
           
      
        
        }else{
        
        }
        
       
       
    }//GEN-LAST:event_btnAddTasksActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnComingSoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComingSoonActionPerformed
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_btnComingSoonActionPerformed

    private void btnQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitMouseClicked
        // TODO add your handling code here:
        
         Dashbord reg = new Dashbord();
         reg.setVisible(false);
         this.setVisible(false);
        
        
    }//GEN-LAST:event_btnQuitMouseClicked

    private void btnComingSoonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComingSoonMouseClicked

        JOptionPane.showMessageDialog(this, "COMING SOON ");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComingSoonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashbord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTasks;
    private javax.swing.JButton btnComingSoon;
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
